#!/usr/bin/env python3
import sys

import cram

# cram doesn't work with UTF-8 for some reason. Disable that restriction:
cram._test._needescape = lambda _: False

try:
    sys.exit(cram.main(sys.argv[1:]))
except KeyboardInterrupt:
    pass
